---
title: "Cook book"
author: "Shelbournator"
date: "22/03/2021"
output: 
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Coursera: Getting and Cleaning Data - Final Assignment

This codebook relies on information in README.Rmd: please start by reading that file.



## dataset.txt

To create the first tidy data set, `dataset.txt`, three new variables were created and 79 were taken from the original data sets.

#### 1. New variables

- `ID` : Subject IDs were taken from "subject_train.txt" and "subject_test.txt" files and added to the dataset.

- `activity` : Activity data were taken from "y_train.txt" and "y_test.txt". These were added to the dataset with labels taken from "activity_labels.txt"

- `dataset` : Shows the dataset that each observation originated from (i.e. test or train)

#### 2. Original variables 

Note : The below information was taken from the original data set, with minor adjustments.

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

- `tBodyAcc-XYZ`
- `tGravityAcc-XYZ`
- `tBodyAccJerk-XYZ`
- `tBodyGyro-XYZ`
- `tBodyGyroJerk-XYZ`
- `tBodyAccMag`
- `tGravityAccMag`
- `tBodyAccJerkMag`
- `tBodyGyroMag`
- `tBodyGyroJerkMag`
- `fBodyAcc-XYZ`
- `fBodyAccJerk-XYZ`
- `fBodyGyro-XYZ`
- `fBodyAccMag`
- `fBodyAccJerkMag`
- `fBodyGyroMag`
- `fBodyGyroJerkMag`

The set of variables that were estimated from these signals are: 

- `mean()`: Mean value
- `std()`: Standard deviation

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

- `gravityMean`
- `tBodyAccMean`
- `tBodyAccJerkMean`
- `tBodyGyroMean`
- `tBodyGyroJerkMean`

## dataset2.txt

`dataset2.txt` was created by transforming `dataset.txt`. It shows the mean of each measurement by subject and activity.

For example, the first row shows the `mean` of all the measurements of `variable` == 'tBodyAcc.mean...X' when `ID` == '1' and  `activity` == 'Laying'.

Variables:

- `variable`
- `activity`
- `ID`
- `mean`
