---
title: "README"
author: "Shelbournator"
date: "22/03/2021"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Coursera: Getting and Cleaning Data - Final Assignment
#### Project overview :
Collect, work with, and clean a dataset. 

#### Data set:

Human Activity Recognition Using Smartphones Dataset - Version 1.0 (HAR)

Accessed at:  https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

#### Scope: 

1. Merge the training and the test sets to create one data set. 
2. Extract only the measurements on the mean and standard deviation for each measurement.
3. Use descriptive activity names to name the activities in the data set
4. Appropriately label the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

#### Run_analysis.R

The `run_analysis.R` completes the tasks outlined in the scope section above, outputting two tidy data sets: `dataset.txt` and `dataset2.txt`. The script itself outlines the steps taken to achieve these data sets.

- **dataset.txt**

The `dataset.txt` file fulfills requirements 1 through 4 of the scope. It is available as a .txt file that can be read into R using the read.table() function.

- **dataset2.txt**

The `dataset2.txt` file fulfills requirement 5 of the scope. It is available as a .txt file, which can be read into R using the read.table() function.


#### Description (adapted from original): 

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See "Codebook.MD" for further details.

For each record the data set provides:

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

#### Files

The following files are available in the main directory:

- "dataset.csv"
- "dataset2.csv"
- "README.md"
- "Cookbook.md"
- "run_analysis.R"

./data directory:

- UCI HAR Dataset (original dataset)

## See "Cookbook.md" for further details.
